version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm run dev
          wait-on: "http://localhost:3000"
          no-workspace: true
          post-steps:
            - store_artifacts:
                path: coverage/lcov-report
